### ISSUE TITLE
Encoding handling utility function

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#12]
We need a central utility function that could be used by any function that deals with users input (e.g., users' script, users' email contents). 

f: users' input -> strings with the encoding that are compatible within youps/murmur

YoUPS and Murmur are currently storing the string data as utf-8 or utf8mb4_general_ci.

**Comment by soyapark** [comment]
Murmur also has this issue so if we can make one function that both YoUPS and Murmur can use, it'd be really nice! 

16:04:24,540 - root - ERROR - Failed to send message to host localhost:587
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/lamson/server.py", line 115, in deliver
    relay_host.sendmail(sender, recipient, str(message))
  File "/home/ubuntu/production/mailx/smtp_handler/lamson_subclass.py", line 129, in __str__
    return self.to_message().as_string()
  File "/home/ubuntu/production/mailx/smtp_handler/lamson_subclass.py", line 194, in to_message
    return to_message(self.base)
  File "/home/ubuntu/production/mailx/smtp_handler/lamson_subclass.py", line 327, in to_message
    out.attach(to_message(part))
  File "/home/ubuntu/production/mailx/smtp_handler/lamson_subclass.py", line 327, in to_message
    out.attach(to_message(part))
  File "/home/ubuntu/production/mailx/smtp_handler/lamson_subclass.py", line 323, in to_message
    out.extract_payload(mail)
  File "/home/ubuntu/production/mailx/smtp_handler/lamson_subclass.py", line 369, in extract_payload
    self.add_html(mail.body)
  File "/home/ubuntu/production/mailx/smtp_handler/lamson_subclass.py", line 355, in add_html
    content = content.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1394: ordinal not in range(128)

**Comment by lukesmurray** [comment]
I left this comment on your other pull request, but can you tell me where you want the string handling function to be?

**Comment by soyapark** [comment]
There is [smtp_handler/utils.py](https://github.com/soyapark/murmur/blob/master/smtp_handler/utils.py) file, but they are more like utility functions for email handling. What about creating `utils.py` under engine/?

**Comment by lukesmurray** [comment]
on #80 I've been playing around with encoding everything using unicode and have not run into any issues storing it in the database or returning it to the user since we fixed the database column issue.
