### ISSUE TITLE
Encoding issue while syncing mailbox

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#37]
```
2019-03-01 23:32:48 DEBUG    [folder.py:113] folder: [Gmail]/Trash finished completely refreshing cache
2019-03-01 23:32:48 ERROR    [mailbot.py:46] mailbox sync failed
Traceback (most recent call last):
  File "/home/ubuntu/production/mailx/smtp_handler/management/commands/mailbot.py", line 42, in handle
    mailbox._sync()
  File "/home/ubuntu/production/mailx/browser/models/mailbox.py", line 47, in _sync
    for folder in self._list_selectable_folders():
  File "/home/ubuntu/production/mailx/browser/models/mailbox.py", line 121, in _list_selectable_folders
    for child_folder in self._list_selectable_folders(name + delimiter):
  File "/home/ubuntu/production/mailx/browser/models/mailbox.py", line 107, in _list_selectable_folders
    folder = self._find_or_create_folder(name)  # type: Folder
  File "/home/ubuntu/production/mailx/browser/models/mailbox.py", line 88, in _find_or_create_folder
    imap_account=self._imap_account, name=name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='")
```

**Comment by soyapark** [comment]
This looked like potentially fixed! let me know if you run into this issue on different column of the table. I know how to fix it

**Comment by lukesmurray** [comment]
we need to find a way to fix this more long term either in mysql configuration files or in the settings.py. I looked into this issue and TEXT fields seemed to all be using utf8mb4 while VARCHAR fields were using latin1. I'm not sure if that is coming from django or if we were manually changing the fields on the older databases.

**Comment by soyapark** [comment]
I've been manually changing one by one field whenever it crashes :D

**Comment by lukesmurray** [comment]
Ok I would like to make it automatic. [Here is one option]( https://django-mysql.readthedocs.io/en/latest/checks.html#django-mysql-w003-utf8mb4) which we could try in the django settings but [based on other posts](https://exana.io/community/a-helping-hand/2016/08/23/django-utf8mb4-selected-columns.html) I don't know if that will actually convert everything.

**Comment by lukesmurray** [comment]
I fixed this on the development server. I followed the instructions [here](http://blog.manbolo.com/2014/03/31/using-emojis-in-django-model-fields) and appended the following code to `/etc/mysql/my.cnf`. 

```
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```

In order to make these changes happen you need to restart mysql with `sudo service mysql restart`. These changes also are only applied to new databases. I did not look into migrating old databases.

This increases the number of bytes per character so I had to change the max length of our email fields to 191, the reasoning is documented [here](https://mathiasbynens.be/notes/mysql-utf8mb4#column-index-length).

**Comment by soyapark** [comment]
It leads to create an error on third-party apps (e.g., djcelery) which are using char longer than 191. Instead, we can set character sets per table like this:
```
ALTER TABLE
    youps_folder
    CONVERT TO CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

ALTER TABLE
    youps_messages
    CONVERT TO CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

ALTER TABLE
    youps_threads
    CONVERT TO CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

ALTER TABLE
    schema_mailbotmode
    CONVERT TO CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

ALTER TABLE
    schema_imapaccount
    CONVERT TO CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

ALTER TABLE
    schema_action
    CONVERT TO CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

ALTER TABLE
    schema_contact
    CONVERT TO CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;
```

**Comment by lukesmurray** [comment]
I'm going to leave this open until I make a python script which alters the tables like you said. It should probably just read from private.py and execute the sql statements you just listed.
