### ISSUE TITLE
null contact instance

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#96]
Contact instance of message.from_ is always null at `engine/youps.py/run_simulate_on_messages()`

And the following occasionally happens,
```
2019-04-05 08:27:09 ERROR    [MainProcess:88937] [sandbox.py:256] failure running user xxx@gmail.com code
Traceback (most recent call last):
  File "/home/ubuntu/production/mailx/browser/sandbox.py", line 156, in interpret
    "name": event_data.message.from_.name,
  File "/home/ubuntu/production/mailx/browser/models/contact.py", line 43, in name
    return self._schema.name
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by lukesmurray** [comment]
I'm having trouble getting the debugger to display things. Let me know when you have time to work with me on this one.
